---
- name: Install Unzip
  apt: unzip
  update_cache: yes
  state: present

- name: Create osTicket directory if it does not exist
  ansible.builtin.file:
    path: "{{ osticket_install_path }}"
    state: directory
    # mode: '0755'

- name: Download & Unarchive osTicket
  ansible.builtin.unarchive:
    src: "{{ osticket_download_url }}"
    dest: "{{ osticket_install_path }}"
    remote_src: yes