---
- name: Install unzip
  package:
    name: unzip
    state: present
    update_cache: yes

- name: Check if osTicket is already installed
  stat:
    path: "{{ osticket_install_path }}"
  register: osticketinstalled

- name: Creates osTicket folder
  file:
    path: "{{ osticket_install_path }}"
    state: directory
    owner: "{{ osticket_web_owner }}"
    group: "{{ osticket_web_group }}"
  when: not osticketinstalled.stat.exists or osticket_update

- name: Download and extract osTicket
  unarchive:
    src: "{{ osticket_download_url }}"
    remote_src: true
    dest: "{{ osticket_install_path }}"
    owner: "{{ osticket_web_owner }}"
    group: "{{ osticket_web_group }}"
  notify: update permissions
  when: not osticketinstalled.stat.exists or osticket_update
    
- name: Copy Template Config
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ osticket_config_sample }}"
    dest: "{{ osticket_config_file }}"
    mode: 0644
    owner: "{{ osticket_web_owner }}"
    group: "{{ osticket_web_group }}"
  when: not osticketinstalled.stat.exists