---
- name: Converge
  hosts: all
  become: yes
  vars:
    osticket_version: "v1.18"
    mysql_root_password: super-secure-password
    mysql_databases:
      - name: osticket
    mysql_users:
      - name: osticket
        host: "%"
        password: super-secure-password
        priv: "osticket.*:ALL"
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: "osticket.test"
        documentroot: "/var/www/osticket/upload"
        serveralias: "www.osticket.test"
        extra_parameters: |
          ErrorLog ${APACHE_LOG_DIR}/osticket-error.log
          CustomLog ${APACHE_LOG_DIR}/osticket-access.log combined
    php_packages:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cgi
      - php-fpm
      - php-cli
      - php-curl
      - php-gd
      - php-imap
      - php-mbstring
      - php-intl
      - php-apcu
      - php-common
      - php-bcmath

  pre_tasks:
    - name: Install dirmngr to add repository
      apt:
        name: dirmngr
        state: present
        update_cache: yes

    - name: Add PHP source
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

  tasks:
    - name: Include MySQL role
      include_role:
        name: geerlingguy.mysql

    - name: Include Apache role
      include_role:
        name: geerlingguy.apache

    - name: Include PHP role
      include_role:
        name: geerlingguy.php

    - name: Include osTicket role
      include_role:
        name: "lucas_stofaleti.osticket"