---
- name: Converge
  hosts: all
  become: yes
  vars:
    osticket_update: yes
    osticket_version: "v1.16"
    mysql_root_password: super-secure-password
    mysql_databases:
      - name: osticket
    mysql_users:
      - name: osticket
        host: "%"
        password: super-secure-password
        priv: "osticket.*:ALL"
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: "osticket.test"
        documentroot: "/var/www/osticket/upload"
        serveralias: "www.osticket.test"
        extra_parameters: |
          ErrorLog ${APACHE_LOG_DIR}/osticket-error.log
          CustomLog ${APACHE_LOG_DIR}/osticket-access.log combined
    php_packages:
      - php8.0
      - libapache2-mod-php8.0
      - php8.0-mysql
      - php8.0-cgi
      - php8.0-fpm
      - php8.0-cli
      - php8.0-curl
      - php8.0-gd
      - php8.0-imap
      - php8.0-mbstring
      - php8.0-intl
      - php8.0-apcu
      - php8.0-common
      - php8.0-bcmath

  pre_tasks:
    - name: Add PHP source
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

  tasks:
    - name: Include Apache role
      include_role:
        name: geerlingguy.mysql

    - name: Include Apache role
      include_role:
        name: geerlingguy.apache

    - name: Include PHP role
      include_role:
        name: geerlingguy.php

    - name: Include osTicket role
      include_role:
        name: "lucas_stofaleti.osticket"