---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu22
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: Ubuntu20
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: Ubuntu18
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
